# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Create_CSV.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateCSVWindow(object):
    def setupUi(self, CreateCSVWindow):
        CreateCSVWindow.setObjectName("CreateCSVWindow")
        CreateCSVWindow.resize(430, 221)
        CreateCSVWindow.setMinimumSize(QtCore.QSize(430, 221))
        CreateCSVWindow.setMaximumSize(QtCore.QSize(430, 221))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/ep_program_logo_user_acc_zrP_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CreateCSVWindow.setWindowIcon(icon)
        self.label_3 = QtWidgets.QLabel(CreateCSVWindow)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.Logo_label = QtWidgets.QLabel(CreateCSVWindow)
        self.Logo_label.setEnabled(True)
        self.Logo_label.setGeometry(QtCore.QRect(354, 9, 64, 64))
        self.Logo_label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Logo_label.setToolTipDuration(-5)
        self.Logo_label.setText("")
        self.Logo_label.setPixmap(QtGui.QPixmap("img/Ep logo60x60.png"))
        self.Logo_label.setScaledContents(False)
        self.Logo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo_label.setObjectName("Logo_label")
        self.frame = QtWidgets.QFrame(CreateCSVWindow)
        self.frame.setGeometry(QtCore.QRect(10, 80, 411, 131))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setGeometry(QtCore.QRect(240, 90, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.TabBoxLabel = QtWidgets.QLabel(self.frame)
        self.TabBoxLabel.setGeometry(QtCore.QRect(10, 38, 150, 13))
        self.TabBoxLabel.setObjectName("TabBoxLabel")
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setGeometry(QtCore.QRect(356, 10, 42, 20))
        self.toolButton.setObjectName("toolButton")
        self.FileBox = QtWidgets.QLineEdit(self.frame)
        self.FileBox.setGeometry(QtCore.QRect(10, 10, 340, 20))
        self.FileBox.setObjectName("FileBox")
        self.SheetcomboBox = QtWidgets.QComboBox(self.frame)
        self.SheetcomboBox.setGeometry(QtCore.QRect(10, 58, 190, 22))
        self.SheetcomboBox.setObjectName("SheetcomboBox")
        self.StartRowLabel = QtWidgets.QLabel(self.frame)
        self.StartRowLabel.setGeometry(QtCore.QRect(48, 84, 47, 13))
        self.StartRowLabel.setObjectName("StartRowLabel")
        self.StartColBox = QtWidgets.QLineEdit(self.frame)
        self.StartColBox.setGeometry(QtCore.QRect(10, 102, 26, 20))
        self.StartColBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.StartColBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.StartColBox.setObjectName("StartColBox")
        self.StartCollabel = QtWidgets.QLabel(self.frame)
        self.StartCollabel.setGeometry(QtCore.QRect(12, 84, 47, 13))
        self.StartCollabel.setObjectName("StartCollabel")
        self.StartRowBox = QtWidgets.QLineEdit(self.frame)
        self.StartRowBox.setGeometry(QtCore.QRect(46, 102, 26, 20))
        self.StartRowBox.setText("")
        self.StartRowBox.setObjectName("StartRowBox")
        self.EndRowLabel = QtWidgets.QLabel(self.frame)
        self.EndRowLabel.setGeometry(QtCore.QRect(140, 84, 47, 13))
        self.EndRowLabel.setObjectName("EndRowLabel")
        self.EndColBox = QtWidgets.QLineEdit(self.frame)
        self.EndColBox.setGeometry(QtCore.QRect(102, 102, 26, 20))
        self.EndColBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.EndColBox.setObjectName("EndColBox")
        self.EndRowBox = QtWidgets.QLineEdit(self.frame)
        self.EndRowBox.setGeometry(QtCore.QRect(138, 102, 26, 20))
        self.EndRowBox.setObjectName("EndRowBox")
        self.EndColLabel = QtWidgets.QLabel(self.frame)
        self.EndColLabel.setGeometry(QtCore.QRect(104, 84, 47, 13))
        self.EndColLabel.setObjectName("EndColLabel")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(31, 102, 20, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(123, 102, 20, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(CreateCSVWindow)
        self.toolButton.clicked.connect(CreateCSVWindow.browse_for_workbook)
        self.buttonBox.accepted.connect(CreateCSVWindow.ok_button_clicked)
        self.buttonBox.rejected.connect(CreateCSVWindow.cancel_button_clicked)
        self.FileBox.textChanged['QString'].connect(CreateCSVWindow.populate_sheet_cmb)
        QtCore.QMetaObject.connectSlotsByName(CreateCSVWindow)
        CreateCSVWindow.setTabOrder(self.FileBox, self.toolButton)
        CreateCSVWindow.setTabOrder(self.toolButton, self.SheetcomboBox)

    def retranslateUi(self, CreateCSVWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateCSVWindow.setWindowTitle(_translate("CreateCSVWindow", "Create CSV File"))
        self.label_3.setText(_translate("CreateCSVWindow", "Please browse for workbook"))
        self.TabBoxLabel.setText(_translate("CreateCSVWindow", "Choose Sheet name "))
        self.toolButton.setText(_translate("CreateCSVWindow", "..."))
        self.FileBox.setText(_translate("CreateCSVWindow", "Enter file location"))
        self.StartRowLabel.setText(_translate("CreateCSVWindow", "Row"))
        self.StartColBox.setInputMask(_translate("CreateCSVWindow", ">Aa"))
        self.StartCollabel.setText(_translate("CreateCSVWindow", "Col"))
        self.StartRowBox.setInputMask(_translate("CreateCSVWindow", "900"))
        self.EndRowLabel.setText(_translate("CreateCSVWindow", "Row"))
        self.EndColBox.setInputMask(_translate("CreateCSVWindow", ">Aa"))
        self.EndRowBox.setInputMask(_translate("CreateCSVWindow", "900"))
        self.EndColLabel.setText(_translate("CreateCSVWindow", "Col"))
        self.label.setText(_translate("CreateCSVWindow", ":"))
        self.label_2.setText(_translate("CreateCSVWindow", ":"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateCSVWindow = QtWidgets.QDialog()
    ui = Ui_CreateCSVWindow()
    ui.setupUi(CreateCSVWindow)
    CreateCSVWindow.show()
    sys.exit(app.exec_())
